<?php
if (function_exists('acf_add_local_field_group')) :

   acf_add_local_field_group(array(
      'key' => 'group_6367a6a44cd4a',
      'title' => 'About Meta',
      'fields' => array(
         array(
            'key' => 'field_6367a6aceaaf1',
            'label' => 'Top Section',
            'name' => 'top_section',
            'type' => 'group',
            'instructions' => 'Add top section content here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_6367a728632ca',
                  'label' => 'Section Title',
                  'name' => 'section_title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367a759632cb',
                  'label' => 'Section Subtitle',
                  'name' => 'section_subtitle',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367a767632cc',
                  'label' => 'Section Content',
                  'name' => 'section_content',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_6367a77d632cd',
                  'label' => 'Content for mobile',
                  'name' => 'content_for_mobile',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'você pode fazer tudo o que você quiser.',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_6367a86e6ab0d',
                  'label' => 'Section Image',
                  'name' => 'section_image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_6367a7ba632ce',
            'label' => 'Middle Section',
            'name' => 'middle_section',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_6367a7cc632cf',
                  'label' => 'Column 1',
                  'name' => 'column_1',
                  'type' => 'group',
                  'instructions' => 'Add/Type column one contents.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'layout' => 'block',
                  'sub_fields' => array(
                     array(
                        'key' => 'field_6367a7dc632d0',
                        'label' => 'Section Title',
                        'name' => 'section_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                           'width' => '',
                           'class' => '',
                           'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                     ),
                     array(
                        'key' => 'field_6367a7ff632d1',
                        'label' => 'Section Content',
                        'name' => 'section_content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                           'width' => '',
                           'class' => '',
                           'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => '',
                     ),
                  ),
               ),
               array(
                  'key' => 'field_6367a82d632d2',
                  'label' => 'Column 2',
                  'name' => 'column_2',
                  'type' => 'group',
                  'instructions' => 'Add/Type column one contents.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'layout' => 'block',
                  'sub_fields' => array(
                     array(
                        'key' => 'field_6367a82d632d3',
                        'label' => 'Section Title',
                        'name' => 'section_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                           'width' => '',
                           'class' => '',
                           'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                     ),
                     array(
                        'key' => 'field_6367a82d632d4',
                        'label' => 'Section Content',
                        'name' => 'section_content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                           'width' => '',
                           'class' => '',
                           'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => '',
                     ),
                  ),
               ),
            ),
         ),
         array(
            'key' => 'field_6367a8596ab0c',
            'label' => 'About big Image',
            'name' => 'about_big_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_6367a8936ab0e',
            'label' => 'Bottom Section',
            'name' => 'bottom_section',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_6367a8a16ab0f',
                  'label' => 'Section Title 1',
                  'name' => 'section_title_1',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367a8b26ab10',
                  'label' => 'Section Title 2',
                  'name' => 'section_title_2',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367a8b66ab11',
                  'label' => 'Signature',
                  'name' => 'signature',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_template',
               'operator' => '==',
               'value' => 'template-about.php',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_6367a593d9cfd',
      'title' => 'FAQ Meta',
      'fields' => array(
         array(
            'key' => 'field_6367a593eec17',
            'label' => 'Section Title',
            'name' => 'section_title',
            'type' => 'text',
            'instructions' => 'Add/type section title here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_6367a593f28e9',
            'label' => 'Button Text',
            'name' => 'button_text',
            'type' => 'text',
            'instructions' => 'Add/Type button text here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Ver todos',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_6367a59402302',
            'label' => 'Button Link',
            'name' => 'button_link',
            'type' => 'url',
            'instructions' => 'Add button link here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
         ),
         array(
            'key' => 'field_6367a59405d3f',
            'label' => 'Accordions',
            'name' => 'accordions',
            'type' => 'repeater',
            'instructions' => 'Add accordion here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_6367a59423dfb',
                  'label' => 'Accordion Heading',
                  'name' => 'accordion_heading',
                  'type' => 'text',
                  'instructions' => 'Add/Type accordion heading here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367a59427aa3',
                  'label' => 'Accordion Body',
                  'name' => 'accordion_body',
                  'type' => 'textarea',
                  'instructions' => 'Add/Type accordion body here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_template',
               'operator' => '==',
               'value' => 'template-faq.php',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_6367ae6c4d42a',
      'title' => 'Footer Settings',
      'fields' => array(
         array(
            'key' => 'field_6367aeb7a1392',
            'label' => 'Footer Style',
            'name' => 'footer_style',
            'type' => 'select',
            'instructions' => 'Select footer style form here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'choices' => array(
               'primary' => 'Primary',
               'secondary' => 'Secondary',
            ),
            'default_value' => 'primary',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '93',
            ),
         ),
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '165',
            ),
         ),
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '97',
            ),
         ),
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '95',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_636880436a5f2',
      'title' => 'Header Settings',
      'fields' => array(
         array(
            'key' => 'field_6368804378d07',
            'label' => 'Header Style',
            'name' => 'header_style',
            'type' => 'select',
            'instructions' => 'Select footer style form here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'choices' => array(
               'primary' => 'Primary',
               'secondary' => 'Secondary',
            ),
            'default_value' => 'primary',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '93',
            ),
         ),
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '165',
            ),
         ),
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '97',
            ),
         ),
         array(
            array(
               'param' => 'page',
               'operator' => '==',
               'value' => '95',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_636266e704b72',
      'title' => 'Home Meta',
      'fields' => array(
         array(
            'key' => 'field_636266f443e54',
            'label' => 'Slider',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63626769ab917',
            'label' => 'Slides',
            'name' => 'slides',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_63626786ab918',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                  'instructions' => 'Add/Type slide title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6362679aab919',
                  'label' => 'Description',
                  'name' => 'description',
                  'type' => 'textarea',
                  'instructions' => 'Add/Type slide description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_636267a3ab91a',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Add/Type button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Catálogo',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636267adab91b',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'https://example.com/',
               ),
               array(
                  'key' => 'field_636267c1ab91c',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => 'Add slide image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'medium',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636346161cf3d',
            'label' => 'Intro',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6367376e7639a',
            'label' => 'Intro Section Title',
            'name' => 'intro_section_title',
            'type' => 'text',
            'instructions' => 'Type/Add intro section title.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636737cd7639b',
            'label' => 'Intro Image for Desktop',
            'name' => 'intro_image_for_desktop',
            'type' => 'image',
            'instructions' => 'Add intro image for desktop.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_636737f47639c',
            'label' => 'Intro Column 1',
            'name' => 'intro_column_1',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '33',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636738347639d',
                  'label' => 'Column Title',
                  'name' => 'column_title',
                  'type' => 'text',
                  'instructions' => 'Type/Add column title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636738557639e',
                  'label' => 'Column Description',
                  'name' => 'column_description',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add column description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 4,
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_636738867639f',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Add/Type button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636738ac763a0',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Add/Paste button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636738d3763a1',
                  'label' => 'Column Image',
                  'name' => 'column_image',
                  'type' => 'image',
                  'instructions' => 'Add column image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636739660a26e',
            'label' => 'Intro Column 2',
            'name' => 'intro_column_2',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '33',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_63673b42dc8b9',
                  'label' => 'Column Title',
                  'name' => 'column_title',
                  'type' => 'text',
                  'instructions' => 'Add/Type column title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636739660a270',
                  'label' => 'Column Description',
                  'name' => 'column_description',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add column description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 4,
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_636739660a271',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Add/Type button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636739660a272',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Add/Paste button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636739660a273',
                  'label' => 'Column Image',
                  'name' => 'column_image',
                  'type' => 'image',
                  'instructions' => 'Add column image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
               array(
                  'key' => 'field_63673b6cdc8ba',
                  'label' => 'Column Title 2',
                  'name' => 'column_title_2',
                  'type' => 'text',
                  'instructions' => 'Add/Type column title 2 here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63673b80dc8bb',
                  'label' => 'Column Description 2',
                  'name' => 'column_description_2',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add column description 2 here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 4,
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_63673b84dc8bc',
                  'label' => 'Button Text 2',
                  'name' => 'button_text_2',
                  'type' => 'text',
                  'instructions' => 'Add/Type button text 2 here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63673b89dc8bd',
                  'label' => 'Button Link 2',
                  'name' => 'button_link_2',
                  'type' => 'url',
                  'instructions' => 'Add/Paste button link 2 here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_6367396e0a274',
            'label' => 'Intro Column 3',
            'name' => 'intro_column_3',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '33',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_6367396e0a275',
                  'label' => 'Column Title',
                  'name' => 'column_title',
                  'type' => 'text',
                  'instructions' => 'Type/Add column title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367396e0a276',
                  'label' => 'Column Description',
                  'name' => 'column_description',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add column description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 4,
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_6367396e0a277',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Add/Type button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367396e0a278',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Add/Paste button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_6367396e0a279',
                  'label' => 'Column Image',
                  'name' => 'column_image',
                  'type' => 'image',
                  'instructions' => 'Add column image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_6363462d1cf3e',
            'label' => 'Features',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6367446831ddc',
            'label' => 'Features',
            'name' => 'features',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 4,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_6367447931ddd',
                  'label' => 'Feature Title',
                  'name' => 'feature_title',
                  'type' => 'text',
                  'instructions' => 'Add/Type feature title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6367449331dde',
                  'label' => 'Feature Description',
                  'name' => 'feature_description',
                  'type' => 'textarea',
                  'instructions' => 'Add/Type feature description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 2,
                  'new_lines' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_6363467e1cf3f',
            'label' => 'Gallery',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_636346891cf40',
            'label' => 'Galleries',
            'name' => 'galleries',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'insert' => 'append',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_636358e1f6398',
            'label' => 'Products',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63673083bec1e',
            'label' => 'Select Products',
            'name' => 'select_products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'post_type' => array(
               0 => 'product-page',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
         ),
         array(
            'key' => 'field_636349afd1da4',
            'label' => 'Problems',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_636349bfd1da5',
            'label' => 'Section Title',
            'name' => 'prblem_section_title',
            'type' => 'text',
            'instructions' => 'Type/Add section title here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636349e2d1da6',
            'label' => 'Section Content',
            'name' => 'problem_section_content',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636349f3d1da7',
                  'label' => 'Content Title',
                  'name' => 'content_title',
                  'type' => 'text',
                  'instructions' => 'Type/Add content title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63634a0cd1da8',
                  'label' => 'Content Description',
                  'name' => 'content_description',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add content description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_63634a48d1dab',
                  'label' => 'Content Image',
                  'name' => 'content_image',
                  'type' => 'image',
                  'instructions' => 'Add content image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
               array(
                  'key' => 'field_63634a1cd1da9',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Type/Add button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Mais',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63634a27d1daa',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_6367520d1422d',
            'label' => 'Contact',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6367521c1422e',
            'label' => 'Contact Section Title',
            'name' => 'contact_section_title',
            'type' => 'text',
            'instructions' => 'Add/Type section title here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636752871422f',
            'label' => 'Form Shortcode',
            'name' => 'form_shortcode',
            'type' => 'text',
            'instructions' => 'Add contact form shortcode here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '[contact-form-7 id="150" title="Home Contact"]',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_63634e1192daa',
            'label' => 'FAQs',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63634e2892dab',
            'label' => 'FAQ Section Title',
            'name' => 'faq_section_title',
            'type' => 'text',
            'instructions' => 'Type/Add faq section title.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636354006d1ba',
            'label' => 'FAQ Button',
            'name' => 'faq_button',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636354256d1bb',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Type/Add button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6363543b6d1bc',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_63634f803cb70',
            'label' => 'FAQ Accordions',
            'name' => 'faq_accordions',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_63634fa89ddbd',
                  'label' => 'Heding',
                  'name' => 'heding',
                  'type' => 'text',
                  'instructions' => 'Type/Add accordion heading.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63634fb29ddbe',
                  'label' => 'Body',
                  'name' => 'body',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add accordion body.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636757a86b6ba',
            'label' => 'Instagram Feed',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6367590215c97',
            'label' => 'Instagram Feed ShortCode',
            'name' => 'instagram_feed_shortcode',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_template',
               'operator' => '==',
               'value' => 'template-home.php',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_63688400cf846',
      'title' => 'Monta Options',
      'fields' => array(
         array(
            'key' => 'field_63688abda582a',
            'label' => 'Header',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6368844a2a8d9',
            'label' => 'Desktop Logo',
            'name' => 'desktop_logo',
            'type' => 'image',
            'instructions' => 'Add header desktop logo.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_636884612a8da',
            'label' => 'Mobile Logo',
            'name' => 'mobile_logo',
            'type' => 'image',
            'instructions' => 'Add header mobile logo.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_63688d60febc1',
            'label' => 'Socials',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63688d6ffebc2',
            'label' => 'Socials',
            'name' => 'socials',
            'type' => 'group',
            'instructions' => 'Add social link here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_63688db2febc3',
                  'label' => 'Instagram',
                  'name' => 'instagram',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'https://www.example.com/username/',
               ),
               array(
                  'key' => 'field_63688dcbfebc4',
                  'label' => 'Facebook',
                  'name' => 'facebook',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'https://www.example.com/username/',
               ),
               array(
                  'key' => 'field_63688dd6febc5',
                  'label' => 'Twitter',
                  'name' => 'twitter',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'https://www.example.com/username/',
               ),
               array(
                  'key' => 'field_63688de0febc6',
                  'label' => 'YouTube',
                  'name' => 'youtube',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'https://www.example.com/username/',
               ),
            ),
         ),
         array(
            'key' => 'field_63688fa63d0da',
            'label' => 'Footer',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63688fddf041a',
            'label' => 'Footer Top',
            'name' => 'footer_top',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_63688fb33d0db',
                  'label' => 'Footer Title',
                  'name' => 'footer_title',
                  'type' => 'text',
                  'instructions' => 'Add/Type footer title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'CONTATO',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6368901bf041b',
                  'label' => 'Footer Email',
                  'name' => 'footer_email',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'digala@monta.la',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6368902bf041c',
                  'label' => 'Footer Phone',
                  'name' => 'footer_phone',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '(406) 555 0120',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63689054f041d',
                  'label' => 'Footer Contact',
                  'name' => 'footer_contact',
                  'type' => 'text',
                  'instructions' => 'Add footer contact shortcode here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '[contact-form-7 id="239" title="Footer Form"]',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636893738bb32',
            'label' => 'Footer Bottom',
            'name' => 'footer_bottom',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636893898bb33',
                  'label' => 'Footer Logo',
                  'name' => 'footer_logo',
                  'type' => 'image',
                  'instructions' => 'Add footer logo here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
               array(
                  'key' => 'field_636893a68bb34',
                  'label' => 'Copyright Text',
                  'name' => 'copyright_text',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'All rights reserved 2022',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'options_page',
               'operator' => '==',
               'value' => 'monta-settings',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_636794b03dc26',
      'title' => 'Problem Meta',
      'fields' => array(
         array(
            'key' => 'field_6367959a45a7b',
            'label' => 'Section Title',
            'name' => 'section_title',
            'type' => 'text',
            'instructions' => 'Add/type section title here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_63679e90cd2b8',
            'label' => 'Button Text',
            'name' => 'button_text',
            'type' => 'text',
            'instructions' => 'Add/Type button text here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Ver todos',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_63679ebdcd2b9',
            'label' => 'Button Link',
            'name' => 'button_link',
            'type' => 'url',
            'instructions' => 'Add button link here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
         ),
         array(
            'key' => 'field_636795c88a789',
            'label' => 'Accordions',
            'name' => 'accordions',
            'type' => 'repeater',
            'instructions' => 'Add accordion here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_636795e18a78a',
                  'label' => 'Accordion Heading',
                  'name' => 'accordion_heading',
                  'type' => 'text',
                  'instructions' => 'Add/Type accordion heading here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636795ef8a78b',
                  'label' => 'Accordion Body',
                  'name' => 'accordion_body',
                  'type' => 'textarea',
                  'instructions' => 'Add/Type accordion body here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_template',
               'operator' => '==',
               'value' => 'template-problem.php',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_636361d2a258a',
      'title' => 'Product Meta',
      'fields' => array(
         array(
            'key' => 'field_6363620395bf3',
            'label' => 'Large Image ?',
            'name' => 'product_large_image',
            'type' => 'radio',
            'instructions' => 'If want to large image for thumbnail.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'choices' => array(
               'yes' => 'Yes',
               'no' => 'No',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => 'no',
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
         ),
         array(
            'key' => 'field_63638a3accda4',
            'label' => 'Product Gallery',
            'name' => 'product_gallery',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'insert' => 'append',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_636380807920e',
            'label' => 'Product Dimension',
            'name' => 'product_dimension',
            'type' => 'text',
            'instructions' => 'Type/Add product dimension here.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'h: 62,8cm; l: 80cm; p: 45cm',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_6363816e26a4d',
            'label' => 'Product Price',
            'name' => 'product_price',
            'type' => 'text',
            'instructions' => 'Type/Add product price here.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '$350',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636382ece5944',
            'label' => 'Product Button',
            'name' => 'product_button',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636382fce5945',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Type/Add button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Escolher',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6363831be5946',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_63638336e5947',
                  'label' => 'Button Description',
                  'name' => 'button_description',
                  'type' => 'text',
                  'instructions' => 'Type/Add button description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Você será redirecionado para outro site para concluir a compra.',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636384ca683fa',
            'label' => 'Instagram',
            'name' => 'product_instagram',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636384ec683fb',
                  'label' => 'Instagram Link',
                  'name' => 'instagram_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add instagram link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_63638512683fc',
                  'label' => 'Instagram Label',
                  'name' => 'instagram_label',
                  'type' => 'text',
                  'instructions' => 'Type/Add instagram label here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636388c926c22',
            'label' => 'Social Share',
            'name' => 'social_share',
            'type' => 'group',
            'instructions' => 'Add social share link here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636388df26c23',
                  'label' => 'Instagram',
                  'name' => 'instagram',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636388ea26c24',
                  'label' => 'Facebook',
                  'name' => 'facebook',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636388f326c25',
                  'label' => 'Twitter',
                  'name' => 'twitter',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636388fe26c26',
                  'label' => 'YouTube',
                  'name' => 'youtube',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_type',
               'operator' => '==',
               'value' => 'product-page',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_636791f23a0c9',
      'title' => 'Related Products',
      'fields' => array(
         array(
            'key' => 'field_6367920751b2a',
            'label' => 'Select Related Products',
            'name' => 'select_related_products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'post_type' => array(
               0 => 'product-page',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_type',
               'operator' => '==',
               'value' => 'product-page',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

endif;
