<?php
if (function_exists('acf_add_local_field_group')) :

   acf_add_local_field_group(array(
      'key' => 'group_636266e704b72',
      'title' => 'Home Meta',
      'fields' => array(
         array(
            'key' => 'field_636266f443e54',
            'label' => 'Slider',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63626769ab917',
            'label' => 'Slides',
            'name' => 'slides',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_63626786ab918',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                  'instructions' => 'Add/Type slide title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6362679aab919',
                  'label' => 'Description',
                  'name' => 'description',
                  'type' => 'textarea',
                  'instructions' => 'Add/Type slide description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_636267a3ab91a',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Add/Type button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Catálogo',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_636267adab91b',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'https://example.com/',
               ),
               array(
                  'key' => 'field_636267c1ab91c',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => 'Add slide image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'medium',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636346161cf3d',
            'label' => 'Intro',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6363462d1cf3e',
            'label' => 'Features',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_6363467e1cf3f',
            'label' => 'Gallery',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_636346891cf40',
            'label' => 'Galleries',
            'name' => 'galleries',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'insert' => 'append',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_636358e1f6398',
            'label' => 'Products',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63635902f6399',
            'label' => 'Section Title',
            'name' => 'product_section_title',
            'type' => 'text',
            'instructions' => 'Type/Add section title here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636349afd1da4',
            'label' => 'Problems',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_636349bfd1da5',
            'label' => 'Section Title',
            'name' => 'prblem_section_title',
            'type' => 'text',
            'instructions' => 'Type/Add section title here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636349e2d1da6',
            'label' => 'Section Content',
            'name' => 'problem_section_content',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636349f3d1da7',
                  'label' => 'Content Title',
                  'name' => 'content_title',
                  'type' => 'text',
                  'instructions' => 'Type/Add content title here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63634a0cd1da8',
                  'label' => 'Content Description',
                  'name' => 'content_description',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add content description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
               ),
               array(
                  'key' => 'field_63634a48d1dab',
                  'label' => 'Content Image',
                  'name' => 'content_image',
                  'type' => 'image',
                  'instructions' => 'Add content image here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
               ),
               array(
                  'key' => 'field_63634a1cd1da9',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Type/Add button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Mais',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63634a27d1daa',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_63634e1192daa',
            'label' => 'FAQs',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
         ),
         array(
            'key' => 'field_63634e2892dab',
            'label' => 'FAQ Section Title',
            'name' => 'faq_section_title',
            'type' => 'text',
            'instructions' => 'Type/Add faq section title.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636354006d1ba',
            'label' => 'FAQ Button',
            'name' => 'faq_button',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636354256d1bb',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Type/Add button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6363543b6d1bc',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_63634f803cb70',
            'label' => 'FAQ Accordions',
            'name' => 'faq_accordions',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
               array(
                  'key' => 'field_63634fa89ddbd',
                  'label' => 'Heding',
                  'name' => 'heding',
                  'type' => 'text',
                  'instructions' => 'Type/Add accordion heading.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_63634fb29ddbe',
                  'label' => 'Body',
                  'name' => 'body',
                  'type' => 'textarea',
                  'instructions' => 'Type/Add accordion body.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_template',
               'operator' => '==',
               'value' => 'template-home.php',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

   acf_add_local_field_group(array(
      'key' => 'group_636361d2a258a',
      'title' => 'Product Meta',
      'fields' => array(
         array(
            'key' => 'field_6363620395bf3',
            'label' => 'Large Image ?',
            'name' => 'product_large_image',
            'type' => 'radio',
            'instructions' => 'If want to large image for thumbnail.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'choices' => array(
               'yes' => 'Yes',
               'no' => 'No',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => 'no',
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
         ),
         array(
            'key' => 'field_63638a3accda4',
            'label' => 'Product Gallery',
            'name' => 'product_gallery',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'insert' => 'append',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
         ),
         array(
            'key' => 'field_636380807920e',
            'label' => 'Product Dimension',
            'name' => 'product_dimension',
            'type' => 'text',
            'instructions' => 'Type/Add product dimension here.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'h: 62,8cm; l: 80cm; p: 45cm',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_6363816e26a4d',
            'label' => 'Product Price',
            'name' => 'product_price',
            'type' => 'text',
            'instructions' => 'Type/Add product price here.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '50',
               'class' => '',
               'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '$350',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
         ),
         array(
            'key' => 'field_636382ece5944',
            'label' => 'Product Button',
            'name' => 'product_button',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636382fce5945',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                  'instructions' => 'Type/Add button text here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Escolher',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
               array(
                  'key' => 'field_6363831be5946',
                  'label' => 'Button Link',
                  'name' => 'button_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add button link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_63638336e5947',
                  'label' => 'Button Description',
                  'name' => 'button_description',
                  'type' => 'text',
                  'instructions' => 'Type/Add button description here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => 'Você será redirecionado para outro site para concluir a compra.',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636384ca683fa',
            'label' => 'Instagram',
            'name' => 'product_instagram',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636384ec683fb',
                  'label' => 'Instagram Link',
                  'name' => 'instagram_link',
                  'type' => 'url',
                  'instructions' => 'Type/Add instagram link here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_63638512683fc',
                  'label' => 'Instagram Label',
                  'name' => 'instagram_label',
                  'type' => 'text',
                  'instructions' => 'Type/Add instagram label here.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '50',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
               ),
            ),
         ),
         array(
            'key' => 'field_636388c926c22',
            'label' => 'Social Share',
            'name' => 'social_share',
            'type' => 'group',
            'instructions' => 'Add social share link here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
               'width' => '',
               'class' => '',
               'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
               array(
                  'key' => 'field_636388df26c23',
                  'label' => 'Instagram',
                  'name' => 'instagram',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636388ea26c24',
                  'label' => 'Facebook',
                  'name' => 'facebook',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636388f326c25',
                  'label' => 'Twitter',
                  'name' => 'twitter',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
               array(
                  'key' => 'field_636388fe26c26',
                  'label' => 'YouTube',
                  'name' => 'youtube',
                  'type' => 'url',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                     'width' => '25',
                     'class' => '',
                     'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
               ),
            ),
         ),
      ),
      'location' => array(
         array(
            array(
               'param' => 'post_type',
               'operator' => '==',
               'value' => 'product-page',
            ),
         ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
   ));

endif;
